
version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Build and Test code
          command: mvn clean install
      - run:
          name: Generate Jacoco Report
          command: mvn jacoco:report
      - store_artifacts:
          path: openjpa-jdbc/target/site/jacoco

workflows:
  version: 2
  build:
    jobs:
      - build
